### ISSUE TITLE
puppet-master[8562]: Could not autoload xmpp: Class Xmpp is already defined in Puppet::Reports

### ISSUE THREAD

**Issue by tarjei** [jamtur01/puppet-xmpp#1]
Hi, 

I tried using this plugin by doing a git clone of the repository and placing it in /etc/puppet/modules. Then I configured /etc/puppet/xmpp.yaml and ran added the settings you described in puppet.conf. When I run puppetclient I get:

puppet-master[8562]: Could not autoload xmpp: Class Xmpp is already defined in Puppet::Reports

I have also installed the xmpp gem as you described.

Any tips?

Regards,
Tarjei

**Comment by foobarable** [comment]
I'm having the same issue here as well. Issue appears on the server.

**Comment by jamtur01** [comment]
This  isn't actually a real error. It is a Puppet generic error that masks whatever the underlying error is. You need to run the master in verbose and debug to see the logs for the actual error.
